spring.application.name=demoSaludPlus
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/bdSaludPlus
spring.datasource.username=postgres
spring.datasource.password=Fabri#1306

jwt.secret=ZmFrZS1jaGFuZ2UtbWUtcGxlYXNlLXJlbmF1bmMtYmFzZTY0LXNlY3JldC0xMjM0NTY3OA==
jwt.expiration=3600000

